# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
 
name: Java CI with Maven
 
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
 
jobs:
  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 19
      uses: actions/setup-java@v1
      with:
        java-version: 19
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: BuildDockerImage
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Publish to Docker Repository
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: xiangfeifeng/personal:springbootdemo
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
